### ISSUE TITLE
Effectiveness of F2, Control-X and so on

### ISSUE THREAD

**Issue by grahamperrin** [adsr/mle#18] opened 2019-09-22 12:31 UTC
Re: https://github.com/adsr/mle#user-content-basic-usage and https://github.com/adsr/mle/issues/17#issuecomment-484703362 there's no response to <kbd>F2</kbd> or <kbd>Control</kbd>-<kbd>X</kbd> on FreeBSD. 

Please, what am I missing? 

Should I report a bug in the FreeBSD area? https://www.freshports.org/editors/mle/

```text
root@momh167-gjp4-8570p:~ # date ;  uname -v
Sun Sep 22 13:28:49 BST 2019
FreeBSD 13.0-CURRENT r352535 GENERIC 
root@momh167-gjp4-8570p:~ # pkg query '%o %v %R' mle
editors/mle 1.4.1 FreeBSD
root@momh167-gjp4-8570p:~ # 
```

**Comment by adsr** [comment] 2019-09-22 18:19
I see the same behavior when installing the port but not when compiling from source. Digging.

**Comment by adsr** [comment] 2019-09-22 20:37
Thanks for the report @grahamperrin. I think 31e89a653ab62a24e82f3e362b3d3350a664f6c4 will fix this issue. I'll update the port after fix is confirmed.

To explain what is going on in these last few commits... The editor stores key bindings in a hash map. This hash map is keyed by a struct (`kinput_t`) which contain 3 integer fields (u8, u32, u16), however most systems add padding bytes so that the actual struct in memory looks like (u8, padding24, u32, u16, padding16) totaling 12 bytes. The entire struct is hashed when keying into the map, so the padding bytes matter. The problem is that assigning a `kinput_t` to a struct literal like `input = (kinput_t){..., ..., ...};` leaves the padding bytes undefined.

Surprisingly this bug only surfaced on certain build configurations on FreeBSD. I cannot fully explain why this only affects certain build configurations, nor why the last commit (af0444b5230d793c46925ee8128235c7c8a0ef14) fixed the previously failing functional test but broke all user input for the prod build. In `gdb` the faulty padding bytes were always `0xff` which was part of the last fix, so I presume the compiler made an unlucky guess when sharing the `kinput_t` stack variable.

Commit 31e89a653ab62a24e82f3e362b3d3350a664f6c4 is more vigilant about how `kinput_t` values are set and passed around (`memset` and `memcpy` are used). A unit test for the padding byte issue is included. Another possible fix for this is to define `kinput_t` as a packed struct, however I'm not sure how portable that is or what kind of guarantees are made concerning padding bytes on various systems.

**Comment by adsr** [comment] 2019-09-25 16:38
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240821

**Comment by adsr** [comment] 2019-09-25 21:40
Should be fixed now. Thanks again for the report.

**Closed by adsr** 2019-09-25 21:40 UTC

**Comment by grahamperrin** [comment] 2019-09-29 15:15
Fix confirmed – thanks.
